language: go
go:
- 1.6.2
- 1.7
install:
- go get github.com/tools/godep
- godep restore
script:
  - go install ./...
notifications:
  slack:
    rooms:
      - alternadev:DV4HmorAz8nFcc4rxBdy92ke#backend
