web:
  build: .
  command: 'bash -c ''georenting-server'''
  working_dir: /app/user
  environment:
    PORT: 8080
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres?sslmode=disable'
    REDIS_URL: 'redis://herokuRedis:6379'
    ELASTICSEARCH_URL: 'http://:@herokuElasticsearch:9200'
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
    - herokuRedis
    - herokuElasticsearch
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres?sslmode=disable'
    REDIS_URL: 'redis://herokuRedis:6379'
    ELASTICSEARCH_URL: 'http://:@herokuElasticsearch'
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
    - herokuRedis
    - herokuElasticsearch
  volumes:
    - '.:/app/user'
herokuPostgresql:
  image: postgres
herokuRedis:
  image: redis
herokuElasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
